FEMALES = {'f', 'F'}
MALES = {'m', 'M'}
VALID_OBSERVATIONS = set.union(FEMALES, MALES)
VALID_INSTRUCTIONS = {'-', '|'}
FEMALE = 'FEMALE'
MALE = 'MALE'
AUTOSOMAL_DOMINANT = 'AUTOSOMAL_DOMINANT'
AUTOSOMAL_RECESSIVE = 'AUTOSOMAL_RECESSIVE'
X_LINKED_DOMINANT = 'X_LINKED_DOMINANT'
X_LINKED_RECESSIVE = 'X_LINKED_RECESSIVE'
Y_LINKED = 'Y_LINKED'
AUTOSOMAL_CHROMOSOMES = {'aa', 'AA', 'aA', 'Aa'}
FEMALE_SEX_LINKED_CHROMOSOMES = {'xx', 'XX', 'xX', 'Xx'}
MALE_SEX_LINKED_CHROMOSOMES = {'xy', 'XY', 'xY', 'Xy'}

ALL_MODES = (AUTOSOMAL_DOMINANT, AUTOSOMAL_RECESSIVE,
             X_LINKED_DOMINANT, X_LINKED_RECESSIVE,
             Y_LINKED)

AUTOSOMAL_MODES = {AUTOSOMAL_DOMINANT, AUTOSOMAL_RECESSIVE}

SEX_LINKED_MODES = {X_LINKED_DOMINANT, X_LINKED_RECESSIVE,
                    Y_LINKED}

